apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
        - name: django
          image: saurabjkawde31/django-notes-app:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: django-env
          command: ["/bin/sh", "-c"]
          args:
            - python manage.py migrate --noinput &&
              gunicorn notesapp.wsgi:application --bind 0.0.0.0:8000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

